name: Test Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Codi de checkout
      uses: actions/checkout@v3
    - name: Python configuració
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Dependències i instal·lació
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Executar tests amb Pytest
      run: |
        pytest